#!/usr/bin/env python3
"""
Email Approval Request Creator
Helper utility to create email approval requests for Human-in-the-Loop workflow
"""

import sys
import json
from pathlib import Path
from datetime import datetime


def create_email_approval(to: str, subject: str, body: str, output_dir: Path = None):
    """Create an email approval request file"""

    # Default output directory
    if output_dir is None:
        base_dir = Path(__file__).parent.parent.parent
        output_dir = base_dir / "Pending_Approval" / "email"

    # Ensure directory exists
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate filename with timestamp
    timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
    filename = f"email_approval_{timestamp}.md"
    filepath = output_dir / filename

    # Create approval file content
    content = f"""---
action: send_email
to: {to}
subject: {subject}
timestamp: {datetime.utcnow().isoformat()}Z
status: pending
---

body:
{body}

---

## Instructions for Human Approval

To APPROVE this email:
1. Review the email details above
2. Move this file to: /Approved/
3. The orchestrator will automatically send the email

To REJECT this email:
1. Move this file to: /Rejected/
2. The orchestrator will log the rejection

DO NOT edit this file. Simply move it to the appropriate folder.
"""

    # Write file
    with open(filepath, 'w') as f:
        f.write(content)

    print(f"✓ Email approval request created: {filepath}")
    print(f"  To: {to}")
    print(f"  Subject: {subject}")
    print(f"\nWaiting for human approval...")
    print(f"  Move to /Approved/ to send")
    print(f"  Move to /Rejected/ to cancel")

    return filepath


def main():
    """Main entry point for CLI usage"""
    if len(sys.argv) < 4:
        print("Usage: python3 create_email_approval.py <to> <subject> <body>")
        print("\nExample:")
        print('  python3 create_email_approval.py "user@example.com" "Test Email" "This is a test message"')
        sys.exit(1)

    to = sys.argv[1]
    subject = sys.argv[2]
    body = sys.argv[3]

    create_email_approval(to, subject, body)


if __name__ == "__main__":
    main()
