#!/usr/bin/env python3
"""
Gold Tier Integration Example for Accounting Core

Demonstrates how to integrate accounting_core with IntegrationOrchestrator
for autonomous operation.

This example shows:
1. Initializing accounting with Gold Tier components
2. Subscribing to accounting events
3. Creating autonomous workflows
4. Handling abnormal cashflow alerts

ARCHITECTURAL NOTE:
This file does NOT import Skills directly. It receives an orchestrator
instance and uses EventBus/SkillRegistry for all interactions.
"""

import sys
from pathlib import Path
from datetime import datetime

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))


def setup_accounting_with_gold_tier(orchestrator):
    """
    Setup accounting_core with Gold Tier integration

    Args:
        orchestrator: IntegrationOrchestrator instance

    Returns:
        None (accounting is accessed via SkillRegistry)
    """
    print("\n" + "=" * 60)
    print("Setting up Accounting Core with Gold Tier")
    print("=" * 60)

    # Register skill with SkillRegistry
    print("\n1. Registering with SkillRegistry...")
    orchestrator.skill_registry.register_skill(
        'accounting_core',
        metadata={
            'description': 'Internal accounting system',
            'version': '1.0',
            'capabilities': ['revenue_tracking', 'expense_tracking', 'reporting']
        }
    )
    print("✓ Skill registered")

    print("\n" + "=" * 60)
    print("Accounting Core ready for Gold Tier operation")
    print("=" * 60)


def setup_event_handlers(orchestrator):
    """
    Setup event handlers for autonomous operation

    Args:
        orchestrator: IntegrationOrchestrator instance
    """
    print("\n" + "=" * 60)
    print("Setting up Event Handlers")
    print("=" * 60)

    # Handler for transaction added
    def on_transaction_added(data):
        print(f"\n[Event] Transaction added:")
        print(f"  Type: {data['type']}")
        print(f"  Amount: ${data['amount']:.2f}")
        print(f"  Category: {data['category']}")
        print(f"  Status: {data['status']}")

    # Handler for reports generated
    def on_reports_generated(data):
        print(f"\n[Event] Reports generated:")
        print(f"  Net Profit: ${data['profit_loss']['net_profit']:.2f}")
        print(f"  Profit Margin: {data['profit_loss']['profit_margin_percent']:.2f}%")
        print(f"  Abnormal Cashflow: {data['cashflow_abnormal']}")

    # Handler for abnormal cashflow (CRITICAL)
    def on_abnormal_cashflow(data):
        print(f"\n⚠ [ALERT] Abnormal Cashflow Detected!")
        print(f"  Consecutive negative weeks: {data['consecutive_negative_weeks']}")

        # Create escalation file in Needs_Action
        timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
        escalation_file = orchestrator.needs_action_dir / f"CASHFLOW_ALERT_{timestamp}.md"

        escalation_content = f"""# Cashflow Alert - Immediate Action Required

## Summary
Abnormal cashflow pattern detected by accounting_core skill.

## Details
- **Consecutive Negative Weeks**: {data['consecutive_negative_weeks']}
- **Detection Time**: {data['timestamp']}
- **Severity**: HIGH

## Cashflow Analysis
The system has detected {data['consecutive_negative_weeks']} consecutive weeks of negative cashflow.
This indicates expenses are exceeding revenue and requires immediate attention.

## Recommended Actions
1. Review weekly cashflow report: `Reports/accounting/cashflow_latest.json`
2. Identify major expense categories
3. Review revenue pipeline
4. Develop action plan to:
   - Reduce non-essential expenses
   - Accelerate revenue collection
   - Secure additional funding if needed

## Next Steps
- [ ] Review cashflow report
- [ ] Identify root causes
- [ ] Create action plan
- [ ] Implement corrective measures
- [ ] Monitor weekly for improvement

## Report Location
See full report in: `Reports/accounting/`

---
Generated by accounting_core skill
Escalated via AutonomousExecutor
"""

        with open(escalation_file, 'w') as f:
            f.write(escalation_content)

        print(f"  ✓ Escalation file created: {escalation_file.name}")

        # Audit log the escalation
        orchestrator.audit_logger.log_event(
            event_type='accounting_escalation',
            actor='accounting_core',
            action='create_cashflow_alert',
            resource='cashflow_monitoring',
            result='escalated',
            metadata={
                'consecutive_negative_weeks': data['consecutive_negative_weeks'],
                'escalation_file': escalation_file.name
            }
        )

    # Subscribe to events
    print("\n1. Subscribing to accounting events...")
    orchestrator.event_bus.subscribe('accounting_transaction_added', on_transaction_added)
    orchestrator.event_bus.subscribe('accounting_reports_generated', on_reports_generated)
    orchestrator.event_bus.subscribe('accounting_abnormal_cashflow', on_abnormal_cashflow)
    print("✓ Event handlers registered")

    print("\n" + "=" * 60)
    print("Event handlers ready")
    print("=" * 60)


def demo_basic_operations(orchestrator):
    """
    Demonstrate basic accounting operations via SkillRegistry

    Args:
        orchestrator: IntegrationOrchestrator instance
    """
    print("\n" + "=" * 60)
    print("Demo: Basic Operations")
    print("=" * 60)

    # Add revenue via SkillRegistry
    print("\n1. Adding revenue transactions via SkillRegistry...")
    orchestrator.skill_registry.execute_skill('accounting_core', ['add-revenue', '--amount', '5000', '--category', 'Consulting', '--description', 'Project Alpha'])
    print("✓ Revenue transactions added")

    # Show summary
    print("\n2. Getting summary via SkillRegistry...")
    orchestrator.skill_registry.execute_skill('accounting_core', ['summary'])


def main():
    """Main entry point"""
    print("\n" + "=" * 60)
    print("ACCOUNTING CORE - GOLD TIER INTEGRATION DEMO")
    print("=" * 60)

    # Get base directory
    base_dir = Path(__file__).parent.parent.parent

    # Initialize orchestrator
    print("\n1. Initializing IntegrationOrchestrator...")
    from Skills.integration_orchestrator.index import IntegrationOrchestrator
    orchestrator = IntegrationOrchestrator(base_dir)
    print("✓ Orchestrator initialized")

    # Setup accounting with Gold Tier
    setup_accounting_with_gold_tier(orchestrator)

    # Setup event handlers
    setup_event_handlers(orchestrator)

    # Run demos
    demo_basic_operations(orchestrator)

    # Final summary
    print("\n" + "=" * 60)
    print("DEMO COMPLETE")
    print("=" * 60)
    print("\nAccounting Core is now integrated with Gold Tier!")
    print("\nKey features demonstrated:")
    print("  ✓ EventBus integration")
    print("  ✓ SkillRegistry registration")
    print("  ✓ Transaction management via SkillRegistry")
    print("  ✓ Abnormal cashflow detection")
    print("\nNext steps:")
    print("  1. Start the orchestrator: python3 Skills/integration_orchestrator/index.py")
    print("  2. Use accounting_core via SkillRegistry")
    print("  3. Monitor events and audit logs")
    print("  4. Review reports in Reports/accounting/")
    print("\n" + "=" * 60)


if __name__ == "__main__":
    main()
