#!/usr/bin/env python3
"""
Gold Tier Integration Example for Weekly CEO Briefing

Demonstrates how to integrate weekly_ceo_briefing with IntegrationOrchestrator
for autonomous weekly report generation.

This example shows:
1. Initializing briefing with Gold Tier components
2. Subscribing to briefing events
3. Creating autonomous weekly triggers
4. Handling critical warnings

ARCHITECTURAL NOTE:
This file does NOT import Skills directly. It receives an orchestrator
instance and uses EventBus/SkillRegistry for all interactions.
"""

import sys
from pathlib import Path
from datetime import datetime

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))


def setup_briefing_with_gold_tier(orchestrator):
    """
    Setup weekly_ceo_briefing with Gold Tier integration

    Args:
        orchestrator: IntegrationOrchestrator instance

    Returns:
        None (briefing is accessed via SkillRegistry)
    """
    print("\n" + "=" * 60)
    print("Setting up Weekly CEO Briefing with Gold Tier")
    print("=" * 60)

    # Register skill with SkillRegistry
    print("\n1. Registering with SkillRegistry...")
    orchestrator.skill_registry.register_skill(
        'weekly_ceo_briefing',
        metadata={
            'description': 'Weekly executive business report',
            'version': '1.0',
            'capabilities': ['reporting', 'analytics', 'recommendations']
        }
    )
    print("✓ Skill registered")

    print("\n" + "=" * 60)
    print("Weekly CEO Briefing ready for Gold Tier operation")
    print("=" * 60)


def setup_event_handlers(orchestrator):
    """
    Setup event handlers for autonomous operation

    Args:
        orchestrator: IntegrationOrchestrator instance
    """
    print("\n" + "=" * 60)
    print("Setting up Event Handlers")
    print("=" * 60)

    # Handler for briefing generated
    def on_briefing_generated(data):
        print(f"\n[Event] CEO Briefing generated:")
        print(f"  Week: {data['week_id']}")
        print(f"  Net Profit: ${data['net_profit']:,.2f}")
        print(f"  Warnings: {data['warnings_count']}")
        print(f"  Recommendations: {data['recommendations_count']}")
        print(f"  Report: {data['report_file']}")

        # If critical warnings, create alert
        if data['warnings_count'] > 0:
            print(f"\n⚠️ {data['warnings_count']} warnings detected!")
            create_warning_alert(orchestrator, data)

    # Subscribe to events
    print("\n1. Subscribing to briefing events...")
    orchestrator.event_bus.subscribe('ceo_briefing_generated', on_briefing_generated)
    print("✓ Event handlers registered")

    print("\n" + "=" * 60)
    print("Event handlers ready")
    print("=" * 60)


def create_warning_alert(orchestrator, briefing_data: dict):
    """
    Create alert file for critical warnings

    Args:
        orchestrator: IntegrationOrchestrator instance
        briefing_data: Briefing event data
    """
    timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
    alert_file = orchestrator.needs_action_dir / f"CEO_BRIEFING_ALERT_{timestamp}.md"

    alert_content = f"""# CEO Briefing Alert - Week {briefing_data['week_id']}

## Summary
The weekly CEO briefing contains {briefing_data['warnings_count']} risk warnings that require attention.

## Details
- **Week:** {briefing_data['week_id']}
- **Net Profit:** ${briefing_data['net_profit']:,.2f}
- **Warnings:** {briefing_data['warnings_count']}
- **Recommendations:** {briefing_data['recommendations_count']}

## Action Required
1. Review the full briefing: `Reports/Weekly/{briefing_data['report_file']}`
2. Address critical warnings identified in the report
3. Implement recommended actions
4. Monitor metrics for improvement

## Report Location
See: `Reports/Weekly/{briefing_data['report_file']}`

---
Generated by weekly_ceo_briefing skill
Alert created: {datetime.utcnow().isoformat()}Z
"""

    with open(alert_file, 'w') as f:
        f.write(alert_content)

    print(f"  ✓ Alert file created: {alert_file.name}")

    # Audit log the alert
    orchestrator.audit_logger.log_event(
        event_type='ceo_briefing_alert',
        actor='weekly_ceo_briefing',
        action='create_warning_alert',
        resource='ceo_briefing_monitoring',
        result='alert_created',
        metadata={
            'week_id': briefing_data['week_id'],
            'warnings_count': briefing_data['warnings_count'],
            'alert_file': alert_file.name
        }
    )


def demo_manual_generation(orchestrator):
    """
    Demonstrate manual briefing generation via SkillRegistry

    Args:
        orchestrator: IntegrationOrchestrator instance
    """
    print("\n" + "=" * 60)
    print("Demo: Manual Briefing Generation")
    print("=" * 60)

    print("\n1. Generating current week's briefing via SkillRegistry...")
    result = orchestrator.skill_registry.execute_skill('weekly_ceo_briefing', ['generate'])

    if result.get('success'):
        print("✓ Briefing generated successfully")
    else:
        print(f"⚠️ Briefing generation failed or skipped: {result.get('error', 'Unknown')}")


def demo_autonomous_weekly_trigger(orchestrator):
    """
    Demonstrate autonomous weekly trigger setup

    Args:
        orchestrator: IntegrationOrchestrator instance
    """
    print("\n" + "=" * 60)
    print("Demo: Autonomous Weekly Trigger")
    print("=" * 60)

    print("\n1. Setting up weekly trigger...")
    print("   This would be added to AutonomousExecutor or PeriodicTrigger")
    print()
    print("   Example code:")
    print("   ```python")
    print("   def check_weekly_briefing():")
    print("       # Get last briefing date")
    print("       last_briefing = state_manager.get_system_state('last_ceo_briefing')")
    print()
    print("       if last_briefing:")
    print("           last_date = datetime.fromisoformat(last_briefing)")
    print("           days_since = (datetime.utcnow() - last_date).days")
    print()
    print("           # If 7+ days since last briefing, generate new one")
    print("           if days_since >= 7:")
    print("               skill_registry.execute_skill('weekly_ceo_briefing', ['generate'])")
    print("               state_manager.set_system_state('last_ceo_briefing',")
    print("                                             datetime.utcnow().isoformat() + 'Z')")
    print("   ```")
    print()
    print("   ✓ Trigger logic defined")

    print("\n2. Checking if briefing is due...")
    last_briefing = orchestrator.state_manager.get_system_state('last_ceo_briefing')

    if last_briefing:
        last_date = datetime.fromisoformat(last_briefing.replace('Z', '+00:00'))
        days_since = (datetime.utcnow() - last_date).days
        print(f"   Last briefing: {days_since} days ago")

        if days_since >= 7:
            print("   ✓ Briefing is due (7+ days)")
        else:
            print(f"   ⏳ Briefing not due yet ({7 - days_since} days remaining)")
    else:
        print("   ℹ️ No previous briefing found")
        print("   ✓ First briefing should be generated")


def main():
    """Main entry point"""
    print("\n" + "=" * 60)
    print("WEEKLY CEO BRIEFING - GOLD TIER INTEGRATION DEMO")
    print("=" * 60)

    # Get base directory
    base_dir = Path(__file__).parent.parent.parent

    # Initialize orchestrator
    print("\n1. Initializing IntegrationOrchestrator...")
    from Skills.integration_orchestrator.index import IntegrationOrchestrator
    orchestrator = IntegrationOrchestrator(base_dir)
    print("✓ Orchestrator initialized")

    # Setup briefing with Gold Tier
    setup_briefing_with_gold_tier(orchestrator)

    # Setup event handlers
    setup_event_handlers(orchestrator)

    # Run demos
    demo_manual_generation(orchestrator)
    demo_autonomous_weekly_trigger(orchestrator)

    # Final summary
    print("\n" + "=" * 60)
    print("DEMO COMPLETE")
    print("=" * 60)
    print("\nWeekly CEO Briefing is now integrated with Gold Tier!")
    print("\nKey features demonstrated:")
    print("  ✓ EventBus integration")
    print("  ✓ SkillRegistry registration")
    print("  ✓ Manual report generation via SkillRegistry")
    print("  ✓ Autonomous weekly triggers")
    print("  ✓ Warning alerts")
    print("\nNext steps:")
    print("  1. Add weekly trigger to AutonomousExecutor")
    print("  2. Configure email notifications")
    print("  3. Review reports regularly")
    print("  4. Act on recommendations and warnings")
    print("\n" + "=" * 60)


if __name__ == "__main__":
    main()
